SatanicLib:
  debugger: true
  currency: Vault #так же можно PlayerPoints
messages:
  bought-success: #можно добавить еще несколько кастомных сообщений
    enable: true
    text:
      - ' '
      - 'Успешно продано {amount}шт за {price}'
      - ' '
  bought-failure: #Если вызывать их через [keyedText] то плейсхолдеров не будет.
    enable: true
    text:
      - ' '
      - 'У вас не хватает предметов. Требуется: {amount} у вас {playerAmount}'
      - ' ' #пробелы обязательно
  bought-failure-all:
    enable: true
    text:
      - ' '
      - 'У вас нет такого предмета'
      - ' '
  home:
    enable: true
    text:
      - ' '
      - 'Добро пожаловать домой'
      - ' '
menus:
  refreshtime: 300 #время в секундах, каждые 5 мин будут обновляться цена на товаре глобально для всех
  categories:
    blockseller: #ID скупщика.
      displayName: "Строитель" #Название для отображения игроку. я не знаю куда это засунуть, пусть будет на всякий случай, для масштабирования
      citizensOverride: #эта графа отвечает за то, что предметы будут переписаны, если меню открыто с помощью команды. #Это декоративный предмет, он не будет продаваться, т.к у него нет цены.
        - id: "stone" #filler
          displayname: "Вы видите это только если открыли через Команду плагина."
          lore:
            - "Какой то крутой текст"
          slotID: 15
          success_commands:
            - '[command] home {player}' #выполняется от имени игрока
            - '[console] say Игрок {player} кликнул на камень и телепортировался домой'
            - '[keyedText] messages.home' #путь к сообщению
      contents: #хранить contents отдельно в виде листа, что бы можно было с помощью команды продать все сразу по текущему прайсу, но по уменьшенной цене
        - id: "stone"
          displayname: " "
          lore:
            - "                  &#8C4CA7Продажа камня"
            - "  "
            - "  &#869D94ЛКМ - 1шт &7| &#869D94ПКМ - 64шт &7| &#869D94ШИФТ+ПКМ - все  "
            - "  "
            - "                   &#869D94Цена: &#5EAC8E${current}"
            - "   "
            - "    &#869D94Цена варьируется от &#5EAC8E{min} &#869D94до &#5EAC8E{max}  "
            - " "
            - "              &#869D94Повышается на: &#5EAC8E{increase}"
            - "    &#869D94за каждые &#5EAC8E{increaseIfSalesUnder}&#869D94 проданных предметов"
            - "  "
            - "              &#869D94Снижается на: &#5EAC8E{decrease}"
            - "    &#869D94за каждые &#5EAC8E{decreaseIfSalesUpwards} &#869D94проданных предметов"
            - " "
            - "               &#5EAC8E{sales} &#869D94- кол-во продаж"
          slotID: 10
          price:
            increaseIfSalesUnder: 5 #Увеличиваем цену только в том случае, если продажи ниже 5; PS это не кол-во продаж, а кол-во проданного товара в штуках. т.е 2 стака = 128
            decreaseIfSalesUpwards: 10 #Уменьшаем цену только в том случае, если продажи выше 10
            default: 20000 #цена за 1шт товара
            min: 10000
            max: 30000
            increaseGradation: 1000
            decreaseGradation: 500
          success_commands:
            - '[command] home {player}' #выполняется от имени игрока
            - '[console] say Игрок {player} купил камень и телепортировался домой'
        - id: "dirt"
          displayname: "Продажа блока земли"
          lore:
            - "Нажмите пкм"
            - "что бы продать траву"
          slotID: 11
          price:
            default: 25000
            min: 5000
            max: 55000
            increaseGradation: 500
            decreaseGradation: 1000
        - id: "glass" #filler который будет 100%, если открыть с NPC или командой
          displayname: "Крутой сервер"
          lore:
            - "Какой то крутой текст"
          slotID: 12